package com.techfun.job.mapper;

import com.techfun.job.entity.JobCategory;
import com.techfun.job.entity.JobCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface JobCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    int countByExample(JobCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    int deleteByExample(JobCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer jobCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    int insert(JobCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    int insertSelective(JobCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    List<JobCategory> selectByExampleWithRowbounds(JobCategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    List<JobCategory> selectByExample(JobCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    JobCategory selectByPrimaryKey(Integer jobCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JobCategory record, @Param("example") JobCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JobCategory record, @Param("example") JobCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JobCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JobCategory record);
}