package com.techfun.job.mapper;

import com.techfun.job.entity.JobDetail;
import com.techfun.job.entity.JobDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface JobDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    int countByExample(JobDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    int deleteByExample(JobDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    int insert(JobDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    int insertSelective(JobDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    List<JobDetail> selectByExampleWithRowbounds(JobDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    List<JobDetail> selectByExample(JobDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    JobDetail selectByPrimaryKey(Integer jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JobDetail record, @Param("example") JobDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JobDetail record, @Param("example") JobDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JobDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JobDetail record);
}