package com.techfun.job.entity;

import java.util.Date;

public class JobCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_category.job_category_id
     *
     * @mbggenerated
     */
    private Integer jobCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_category.job_category_name
     *
     * @mbggenerated
     */
    private String jobCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_category.create_dt
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_category.job_category_id
     *
     * @return the value of job_category.job_category_id
     *
     * @mbggenerated
     */
    public Integer getJobCategoryId() {
        return jobCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_category.job_category_id
     *
     * @param jobCategoryId the value for job_category.job_category_id
     *
     * @mbggenerated
     */
    public void setJobCategoryId(Integer jobCategoryId) {
        this.jobCategoryId = jobCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_category.job_category_name
     *
     * @return the value of job_category.job_category_name
     *
     * @mbggenerated
     */
    public String getJobCategoryName() {
        return jobCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_category.job_category_name
     *
     * @param jobCategoryName the value for job_category.job_category_name
     *
     * @mbggenerated
     */
    public void setJobCategoryName(String jobCategoryName) {
        this.jobCategoryName = jobCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_category.create_dt
     *
     * @return the value of job_category.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_category.create_dt
     *
     * @param createDt the value for job_category.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_category
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobCategoryId=").append(jobCategoryId);
        sb.append(", jobCategoryName=").append(jobCategoryName);
        sb.append(", createDt=").append(createDt);
        sb.append("]");
        return sb.toString();
    }
}