package com.techfun.job.entity;

import java.util.Date;

public class JobDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.job_id
     *
     * @mbggenerated
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.job_category_id
     *
     * @mbggenerated
     */
    private Integer jobCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.post_title
     *
     * @mbggenerated
     */
    private String postTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.job_closing_date
     *
     * @mbggenerated
     */
    private Date jobClosingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.job_description
     *
     * @mbggenerated
     */
    private String jobDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.responsibilities
     *
     * @mbggenerated
     */
    private String responsibilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.skill
     *
     * @mbggenerated
     */
    private String skill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.delete_flg
     *
     * @mbggenerated
     */
    private Integer deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.create_dt
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.update_dt
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.job_location
     *
     * @mbggenerated
     */
    private String jobLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.job_type
     *
     * @mbggenerated
     */
    private String jobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.user_user_id
     *
     * @mbggenerated
     */
    private Integer userUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.job_category_job_category_id
     *
     * @mbggenerated
     */
    private Integer jobCategoryJobCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_detail.how_to_apply
     *
     * @mbggenerated
     */
    private String howToApply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.job_id
     *
     * @return the value of job_detail.job_id
     *
     * @mbggenerated
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.job_id
     *
     * @param jobId the value for job_detail.job_id
     *
     * @mbggenerated
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.job_category_id
     *
     * @return the value of job_detail.job_category_id
     *
     * @mbggenerated
     */
    public Integer getJobCategoryId() {
        return jobCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.job_category_id
     *
     * @param jobCategoryId the value for job_detail.job_category_id
     *
     * @mbggenerated
     */
    public void setJobCategoryId(Integer jobCategoryId) {
        this.jobCategoryId = jobCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.user_id
     *
     * @return the value of job_detail.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.user_id
     *
     * @param userId the value for job_detail.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.company_name
     *
     * @return the value of job_detail.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.company_name
     *
     * @param companyName the value for job_detail.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.post_title
     *
     * @return the value of job_detail.post_title
     *
     * @mbggenerated
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.post_title
     *
     * @param postTitle the value for job_detail.post_title
     *
     * @mbggenerated
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.job_closing_date
     *
     * @return the value of job_detail.job_closing_date
     *
     * @mbggenerated
     */
    public Date getJobClosingDate() {
        return jobClosingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.job_closing_date
     *
     * @param jobClosingDate the value for job_detail.job_closing_date
     *
     * @mbggenerated
     */
    public void setJobClosingDate(Date jobClosingDate) {
        this.jobClosingDate = jobClosingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.job_description
     *
     * @return the value of job_detail.job_description
     *
     * @mbggenerated
     */
    public String getJobDescription() {
        return jobDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.job_description
     *
     * @param jobDescription the value for job_detail.job_description
     *
     * @mbggenerated
     */
    public void setJobDescription(String jobDescription) {
        this.jobDescription = jobDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.responsibilities
     *
     * @return the value of job_detail.responsibilities
     *
     * @mbggenerated
     */
    public String getResponsibilities() {
        return responsibilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.responsibilities
     *
     * @param responsibilities the value for job_detail.responsibilities
     *
     * @mbggenerated
     */
    public void setResponsibilities(String responsibilities) {
        this.responsibilities = responsibilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.skill
     *
     * @return the value of job_detail.skill
     *
     * @mbggenerated
     */
    public String getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.skill
     *
     * @param skill the value for job_detail.skill
     *
     * @mbggenerated
     */
    public void setSkill(String skill) {
        this.skill = skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.delete_flg
     *
     * @return the value of job_detail.delete_flg
     *
     * @mbggenerated
     */
    public Integer getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.delete_flg
     *
     * @param deleteFlg the value for job_detail.delete_flg
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Integer deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.create_dt
     *
     * @return the value of job_detail.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.create_dt
     *
     * @param createDt the value for job_detail.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.update_dt
     *
     * @return the value of job_detail.update_dt
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.update_dt
     *
     * @param updateDt the value for job_detail.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.job_location
     *
     * @return the value of job_detail.job_location
     *
     * @mbggenerated
     */
    public String getJobLocation() {
        return jobLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.job_location
     *
     * @param jobLocation the value for job_detail.job_location
     *
     * @mbggenerated
     */
    public void setJobLocation(String jobLocation) {
        this.jobLocation = jobLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.job_type
     *
     * @return the value of job_detail.job_type
     *
     * @mbggenerated
     */
    public String getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.job_type
     *
     * @param jobType the value for job_detail.job_type
     *
     * @mbggenerated
     */
    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.user_user_id
     *
     * @return the value of job_detail.user_user_id
     *
     * @mbggenerated
     */
    public Integer getUserUserId() {
        return userUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.user_user_id
     *
     * @param userUserId the value for job_detail.user_user_id
     *
     * @mbggenerated
     */
    public void setUserUserId(Integer userUserId) {
        this.userUserId = userUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.job_category_job_category_id
     *
     * @return the value of job_detail.job_category_job_category_id
     *
     * @mbggenerated
     */
    public Integer getJobCategoryJobCategoryId() {
        return jobCategoryJobCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.job_category_job_category_id
     *
     * @param jobCategoryJobCategoryId the value for job_detail.job_category_job_category_id
     *
     * @mbggenerated
     */
    public void setJobCategoryJobCategoryId(Integer jobCategoryJobCategoryId) {
        this.jobCategoryJobCategoryId = jobCategoryJobCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_detail.how_to_apply
     *
     * @return the value of job_detail.how_to_apply
     *
     * @mbggenerated
     */
    public String getHowToApply() {
        return howToApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_detail.how_to_apply
     *
     * @param howToApply the value for job_detail.how_to_apply
     *
     * @mbggenerated
     */
    public void setHowToApply(String howToApply) {
        this.howToApply = howToApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobId=").append(jobId);
        sb.append(", jobCategoryId=").append(jobCategoryId);
        sb.append(", userId=").append(userId);
        sb.append(", companyName=").append(companyName);
        sb.append(", postTitle=").append(postTitle);
        sb.append(", jobClosingDate=").append(jobClosingDate);
        sb.append(", jobDescription=").append(jobDescription);
        sb.append(", responsibilities=").append(responsibilities);
        sb.append(", skill=").append(skill);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", createDt=").append(createDt);
        sb.append(", updateDt=").append(updateDt);
        sb.append(", jobLocation=").append(jobLocation);
        sb.append(", jobType=").append(jobType);
        sb.append(", userUserId=").append(userUserId);
        sb.append(", jobCategoryJobCategoryId=").append(jobCategoryJobCategoryId);
        sb.append(", howToApply=").append(howToApply);
        sb.append("]");
        return sb.toString();
    }
}