package com.techfun.job.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class JobDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public JobDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andJobIdIsNull() {
            addCriterion("job_id is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("job_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(Integer value) {
            addCriterion("job_id =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(Integer value) {
            addCriterion("job_id <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(Integer value) {
            addCriterion("job_id >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_id >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(Integer value) {
            addCriterion("job_id <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(Integer value) {
            addCriterion("job_id <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<Integer> values) {
            addCriterion("job_id in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<Integer> values) {
            addCriterion("job_id not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(Integer value1, Integer value2) {
            addCriterion("job_id between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(Integer value1, Integer value2) {
            addCriterion("job_id not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdIsNull() {
            addCriterion("job_category_id is null");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdIsNotNull() {
            addCriterion("job_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdEqualTo(Integer value) {
            addCriterion("job_category_id =", value, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdNotEqualTo(Integer value) {
            addCriterion("job_category_id <>", value, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdGreaterThan(Integer value) {
            addCriterion("job_category_id >", value, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_category_id >=", value, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdLessThan(Integer value) {
            addCriterion("job_category_id <", value, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("job_category_id <=", value, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdIn(List<Integer> values) {
            addCriterion("job_category_id in", values, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdNotIn(List<Integer> values) {
            addCriterion("job_category_id not in", values, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("job_category_id between", value1, value2, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("job_category_id not between", value1, value2, "jobCategoryId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andPostTitleIsNull() {
            addCriterion("post_title is null");
            return (Criteria) this;
        }

        public Criteria andPostTitleIsNotNull() {
            addCriterion("post_title is not null");
            return (Criteria) this;
        }

        public Criteria andPostTitleEqualTo(String value) {
            addCriterion("post_title =", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleNotEqualTo(String value) {
            addCriterion("post_title <>", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleGreaterThan(String value) {
            addCriterion("post_title >", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleGreaterThanOrEqualTo(String value) {
            addCriterion("post_title >=", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleLessThan(String value) {
            addCriterion("post_title <", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleLessThanOrEqualTo(String value) {
            addCriterion("post_title <=", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleLike(String value) {
            addCriterion("post_title like", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleNotLike(String value) {
            addCriterion("post_title not like", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleIn(List<String> values) {
            addCriterion("post_title in", values, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleNotIn(List<String> values) {
            addCriterion("post_title not in", values, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleBetween(String value1, String value2) {
            addCriterion("post_title between", value1, value2, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleNotBetween(String value1, String value2) {
            addCriterion("post_title not between", value1, value2, "postTitle");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateIsNull() {
            addCriterion("job_closing_date is null");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateIsNotNull() {
            addCriterion("job_closing_date is not null");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateEqualTo(Date value) {
            addCriterionForJDBCDate("job_closing_date =", value, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("job_closing_date <>", value, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateGreaterThan(Date value) {
            addCriterionForJDBCDate("job_closing_date >", value, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("job_closing_date >=", value, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateLessThan(Date value) {
            addCriterionForJDBCDate("job_closing_date <", value, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("job_closing_date <=", value, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateIn(List<Date> values) {
            addCriterionForJDBCDate("job_closing_date in", values, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("job_closing_date not in", values, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("job_closing_date between", value1, value2, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobClosingDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("job_closing_date not between", value1, value2, "jobClosingDate");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionIsNull() {
            addCriterion("job_description is null");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionIsNotNull() {
            addCriterion("job_description is not null");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionEqualTo(String value) {
            addCriterion("job_description =", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotEqualTo(String value) {
            addCriterion("job_description <>", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionGreaterThan(String value) {
            addCriterion("job_description >", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("job_description >=", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLessThan(String value) {
            addCriterion("job_description <", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLessThanOrEqualTo(String value) {
            addCriterion("job_description <=", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLike(String value) {
            addCriterion("job_description like", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotLike(String value) {
            addCriterion("job_description not like", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionIn(List<String> values) {
            addCriterion("job_description in", values, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotIn(List<String> values) {
            addCriterion("job_description not in", values, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionBetween(String value1, String value2) {
            addCriterion("job_description between", value1, value2, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotBetween(String value1, String value2) {
            addCriterion("job_description not between", value1, value2, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesIsNull() {
            addCriterion("responsibilities is null");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesIsNotNull() {
            addCriterion("responsibilities is not null");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesEqualTo(String value) {
            addCriterion("responsibilities =", value, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesNotEqualTo(String value) {
            addCriterion("responsibilities <>", value, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesGreaterThan(String value) {
            addCriterion("responsibilities >", value, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesGreaterThanOrEqualTo(String value) {
            addCriterion("responsibilities >=", value, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesLessThan(String value) {
            addCriterion("responsibilities <", value, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesLessThanOrEqualTo(String value) {
            addCriterion("responsibilities <=", value, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesLike(String value) {
            addCriterion("responsibilities like", value, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesNotLike(String value) {
            addCriterion("responsibilities not like", value, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesIn(List<String> values) {
            addCriterion("responsibilities in", values, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesNotIn(List<String> values) {
            addCriterion("responsibilities not in", values, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesBetween(String value1, String value2) {
            addCriterion("responsibilities between", value1, value2, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andResponsibilitiesNotBetween(String value1, String value2) {
            addCriterion("responsibilities not between", value1, value2, "responsibilities");
            return (Criteria) this;
        }

        public Criteria andSkillIsNull() {
            addCriterion("skill is null");
            return (Criteria) this;
        }

        public Criteria andSkillIsNotNull() {
            addCriterion("skill is not null");
            return (Criteria) this;
        }

        public Criteria andSkillEqualTo(String value) {
            addCriterion("skill =", value, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillNotEqualTo(String value) {
            addCriterion("skill <>", value, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillGreaterThan(String value) {
            addCriterion("skill >", value, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillGreaterThanOrEqualTo(String value) {
            addCriterion("skill >=", value, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillLessThan(String value) {
            addCriterion("skill <", value, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillLessThanOrEqualTo(String value) {
            addCriterion("skill <=", value, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillLike(String value) {
            addCriterion("skill like", value, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillNotLike(String value) {
            addCriterion("skill not like", value, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillIn(List<String> values) {
            addCriterion("skill in", values, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillNotIn(List<String> values) {
            addCriterion("skill not in", values, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillBetween(String value1, String value2) {
            addCriterion("skill between", value1, value2, "skill");
            return (Criteria) this;
        }

        public Criteria andSkillNotBetween(String value1, String value2) {
            addCriterion("skill not between", value1, value2, "skill");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("delete_flg is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("delete_flg is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(Integer value) {
            addCriterion("delete_flg =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(Integer value) {
            addCriterion("delete_flg <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(Integer value) {
            addCriterion("delete_flg >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(Integer value) {
            addCriterion("delete_flg >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(Integer value) {
            addCriterion("delete_flg <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(Integer value) {
            addCriterion("delete_flg <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<Integer> values) {
            addCriterion("delete_flg in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<Integer> values) {
            addCriterion("delete_flg not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(Integer value1, Integer value2) {
            addCriterion("delete_flg between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(Integer value1, Integer value2) {
            addCriterion("delete_flg not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNull() {
            addCriterion("create_dt is null");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNotNull() {
            addCriterion("create_dt is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDtEqualTo(Date value) {
            addCriterion("create_dt =", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotEqualTo(Date value) {
            addCriterion("create_dt <>", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThan(Date value) {
            addCriterion("create_dt >", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_dt >=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThan(Date value) {
            addCriterion("create_dt <", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThanOrEqualTo(Date value) {
            addCriterion("create_dt <=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtIn(List<Date> values) {
            addCriterion("create_dt in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotIn(List<Date> values) {
            addCriterion("create_dt not in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtBetween(Date value1, Date value2) {
            addCriterion("create_dt between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotBetween(Date value1, Date value2) {
            addCriterion("create_dt not between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtIsNull() {
            addCriterion("update_dt is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDtIsNotNull() {
            addCriterion("update_dt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDtEqualTo(Date value) {
            addCriterion("update_dt =", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotEqualTo(Date value) {
            addCriterion("update_dt <>", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtGreaterThan(Date value) {
            addCriterion("update_dt >", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtGreaterThanOrEqualTo(Date value) {
            addCriterion("update_dt >=", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtLessThan(Date value) {
            addCriterion("update_dt <", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtLessThanOrEqualTo(Date value) {
            addCriterion("update_dt <=", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtIn(List<Date> values) {
            addCriterion("update_dt in", values, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotIn(List<Date> values) {
            addCriterion("update_dt not in", values, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtBetween(Date value1, Date value2) {
            addCriterion("update_dt between", value1, value2, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotBetween(Date value1, Date value2) {
            addCriterion("update_dt not between", value1, value2, "updateDt");
            return (Criteria) this;
        }

        public Criteria andJobLocationIsNull() {
            addCriterion("job_location is null");
            return (Criteria) this;
        }

        public Criteria andJobLocationIsNotNull() {
            addCriterion("job_location is not null");
            return (Criteria) this;
        }

        public Criteria andJobLocationEqualTo(String value) {
            addCriterion("job_location =", value, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationNotEqualTo(String value) {
            addCriterion("job_location <>", value, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationGreaterThan(String value) {
            addCriterion("job_location >", value, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationGreaterThanOrEqualTo(String value) {
            addCriterion("job_location >=", value, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationLessThan(String value) {
            addCriterion("job_location <", value, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationLessThanOrEqualTo(String value) {
            addCriterion("job_location <=", value, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationLike(String value) {
            addCriterion("job_location like", value, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationNotLike(String value) {
            addCriterion("job_location not like", value, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationIn(List<String> values) {
            addCriterion("job_location in", values, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationNotIn(List<String> values) {
            addCriterion("job_location not in", values, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationBetween(String value1, String value2) {
            addCriterion("job_location between", value1, value2, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobLocationNotBetween(String value1, String value2) {
            addCriterion("job_location not between", value1, value2, "jobLocation");
            return (Criteria) this;
        }

        public Criteria andJobTypeIsNull() {
            addCriterion("job_type is null");
            return (Criteria) this;
        }

        public Criteria andJobTypeIsNotNull() {
            addCriterion("job_type is not null");
            return (Criteria) this;
        }

        public Criteria andJobTypeEqualTo(String value) {
            addCriterion("job_type =", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotEqualTo(String value) {
            addCriterion("job_type <>", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeGreaterThan(String value) {
            addCriterion("job_type >", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeGreaterThanOrEqualTo(String value) {
            addCriterion("job_type >=", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeLessThan(String value) {
            addCriterion("job_type <", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeLessThanOrEqualTo(String value) {
            addCriterion("job_type <=", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeLike(String value) {
            addCriterion("job_type like", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotLike(String value) {
            addCriterion("job_type not like", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeIn(List<String> values) {
            addCriterion("job_type in", values, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotIn(List<String> values) {
            addCriterion("job_type not in", values, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeBetween(String value1, String value2) {
            addCriterion("job_type between", value1, value2, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotBetween(String value1, String value2) {
            addCriterion("job_type not between", value1, value2, "jobType");
            return (Criteria) this;
        }

        public Criteria andUserUserIdIsNull() {
            addCriterion("user_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserUserIdIsNotNull() {
            addCriterion("user_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserUserIdEqualTo(Integer value) {
            addCriterion("user_user_id =", value, "userUserId");
            return (Criteria) this;
        }

        public Criteria andUserUserIdNotEqualTo(Integer value) {
            addCriterion("user_user_id <>", value, "userUserId");
            return (Criteria) this;
        }

        public Criteria andUserUserIdGreaterThan(Integer value) {
            addCriterion("user_user_id >", value, "userUserId");
            return (Criteria) this;
        }

        public Criteria andUserUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_user_id >=", value, "userUserId");
            return (Criteria) this;
        }

        public Criteria andUserUserIdLessThan(Integer value) {
            addCriterion("user_user_id <", value, "userUserId");
            return (Criteria) this;
        }

        public Criteria andUserUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_user_id <=", value, "userUserId");
            return (Criteria) this;
        }

        public Criteria andUserUserIdIn(List<Integer> values) {
            addCriterion("user_user_id in", values, "userUserId");
            return (Criteria) this;
        }

        public Criteria andUserUserIdNotIn(List<Integer> values) {
            addCriterion("user_user_id not in", values, "userUserId");
            return (Criteria) this;
        }

        public Criteria andUserUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_user_id between", value1, value2, "userUserId");
            return (Criteria) this;
        }

        public Criteria andUserUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_user_id not between", value1, value2, "userUserId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdIsNull() {
            addCriterion("job_category_job_category_id is null");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdIsNotNull() {
            addCriterion("job_category_job_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdEqualTo(Integer value) {
            addCriterion("job_category_job_category_id =", value, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdNotEqualTo(Integer value) {
            addCriterion("job_category_job_category_id <>", value, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdGreaterThan(Integer value) {
            addCriterion("job_category_job_category_id >", value, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_category_job_category_id >=", value, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdLessThan(Integer value) {
            addCriterion("job_category_job_category_id <", value, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("job_category_job_category_id <=", value, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdIn(List<Integer> values) {
            addCriterion("job_category_job_category_id in", values, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdNotIn(List<Integer> values) {
            addCriterion("job_category_job_category_id not in", values, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("job_category_job_category_id between", value1, value2, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andJobCategoryJobCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("job_category_job_category_id not between", value1, value2, "jobCategoryJobCategoryId");
            return (Criteria) this;
        }

        public Criteria andHowToApplyIsNull() {
            addCriterion("how_to_apply is null");
            return (Criteria) this;
        }

        public Criteria andHowToApplyIsNotNull() {
            addCriterion("how_to_apply is not null");
            return (Criteria) this;
        }

        public Criteria andHowToApplyEqualTo(String value) {
            addCriterion("how_to_apply =", value, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyNotEqualTo(String value) {
            addCriterion("how_to_apply <>", value, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyGreaterThan(String value) {
            addCriterion("how_to_apply >", value, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyGreaterThanOrEqualTo(String value) {
            addCriterion("how_to_apply >=", value, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyLessThan(String value) {
            addCriterion("how_to_apply <", value, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyLessThanOrEqualTo(String value) {
            addCriterion("how_to_apply <=", value, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyLike(String value) {
            addCriterion("how_to_apply like", value, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyNotLike(String value) {
            addCriterion("how_to_apply not like", value, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyIn(List<String> values) {
            addCriterion("how_to_apply in", values, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyNotIn(List<String> values) {
            addCriterion("how_to_apply not in", values, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyBetween(String value1, String value2) {
            addCriterion("how_to_apply between", value1, value2, "howToApply");
            return (Criteria) this;
        }

        public Criteria andHowToApplyNotBetween(String value1, String value2) {
            addCriterion("how_to_apply not between", value1, value2, "howToApply");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}